---
- hosts: kubernetes-worker-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=/tmp/join_token remote_src=no

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /tmp/join_token | tail -2 > out.sh
     sh out.sh
